export const UPDATE_MENU = "UPDATE_MENU";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const UPDATE_CURRENT_EVENT = "UPDATE_CURRENT_EVENT";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
export const OPEN_CART="OPEN_CART";


